### ISSUE TITLE
{FIXED} Player  equipping iron gear will instantly get disconnected

### ISSUE THREAD

**Issue by shortybsd** [RedBullSlurpie/SlurpiesDongles#1]
Player equipped full iron vanilla gear then was forcibly disconnected. Every time he tries to log back on my server he is instantly kicked back to the Main screen (no client crash). I had to delete the player's .dat file in order for him to reconnect successfully. Here is the following error:

net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:378) ~[lr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163) ~[mb.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:286) ~[ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [ma.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386) [la.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at com.rbs.slurpiesdongles.events.EventHandler.onPlayerTick(EventHandler.java:19) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_147_EventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:352) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:182) ~[zj.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:301) ~[lr.class:?]
	... 9 more

**Comment by RedBullSlurpie** [comment]
Could you give me a little more info? Perhaps what Minecraft version you are on? What Forge version you are on? A list of other mods that you have in the pack with mine. Thank you.

**Comment by shortybsd** [comment]
For sure brother,
MC version 1.9
Forge 1862
and the mods are the following:

ArmorHud-1.8.9-2.0.1 
BaseMetals_1.9-2.1.1 
BiomesOPlenty-1.9-4.0.2.2009-universal 
BloodMagic-1.9-2.0.0-31 
Bookshelf-API-1.9-3.0.4 
Chisel-MC1.9-0.0.4.13 
chiselsandbits-9.13 
ChunkLoaderZ-1.9-1.1 
CookingForBlockheads-mc1.9-2.0.5 
CustomMainMenu-MC1.9-2.0 
ElectricAdvantage-2.0.1 
enderutilities-1.9-0.5.1 
fastTravel-1.9-1.0.1-universal 
graves-1.9-b8-universal 
ironchest-1.9-6.0.132.776 
JAPTA-1.9-1.4.1 
jei_1.9-3.2.10.185 
journeymap-1.9-5.1.6b2-unlimited 
k4lib-1.9-1.0.4-universal 
Mantle-1.9-0.9.4 
mcjtylib-1.9.0-1.8.1beta15 
modnametooltip_1.9-1.3.0 
ModularSystems-1.9-3.0.2 
NeoTech-1.9-3.0.5 
notenoughwands-1.9.0-1.3.1 
PowerAdvantage_1.9.0-2.0.2 
ProgressiveAutomation-1.9-1.6.38 
Psi-beta-31 
quantumflux-1.9-2.0.4 
RandomThings-MC1.9-3.6.9 
RebornCore-1.9-2.0.4.46-universal 
refinedstorage-0.5.5 
rftools-1.9.0-4.23beta42 
Slurpie's Dongles-1.9-3.0.2 
SteamAdvantage-2.0.1 
TConstruct-1.9-2.2.2 
TechReborn-1.9-1.0.4.143-universal 
Waila-1.7.0-B2_1.9

**Comment by RedBullSlurpie** [comment]
Fixed the issue. Will be uploading a new file soon that fixes the issue. Thank you for taking the time to report the issue to me, if you find anymore issues, dont hesitate to post them! Hope you enjoy the mod. :)

**Comment by shortybsd** [comment]
Awesome man, thank you and also thank you for being a great mod author. Any idea when a new build will be posted? I'll keep refreshing in the meantime :P

**Comment by RedBullSlurpie** [comment]
Yes, I am getting ready to eat dinner, I shall upload a new build afterwards. It takes some time to upload, so I'd say within the hour it should be up. :)

**Comment by shortybsd** [comment]
Sweet, many thanks brother!

**Comment by RedBullSlurpie** [comment]
Uploaded the file, give it some time to be approved, and it should show up for you. Should take anywhere from 5-30 minutes.
